language: r
dist: bionic
cache: packages

r_packages:
  - ggplot2
  - knitr
  - rmarkdown
  - stringr
  - testthat

install:
  - sudo apt install r-cran-rmarkdown
  - sudo apt install csv2latex

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz
  - make

after_script:
  # The file should be created
  - if [[ ! -f "article.pdf" ]]; then echo "File 'article.pdf' not created "; exit 1; fi
  # After a make, all should be done
  - if [ "$(make)" != "make: Nothing to be done for 'all'." ]; then echo "second make should do nothing"; exit 1; fi

